# Generated by Django 5.0.9 on 2024-09-16 19:45

import django.db.models.deletion
import sortedm2m.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthletesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Vorname')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsoren',
            },
        ),
        migrations.CreateModel(
            name='AthletePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('birthdate', models.DateField(verbose_name='Geburtsdatum')),
                ('discipline', models.CharField(max_length=50, verbose_name='Sportart')),
                ('nationality', models.CharField(max_length=50, verbose_name='Nationalität')),
                ('career_start', models.IntegerField(blank=True, verbose_name='career_start')),
                ('bio', wagtail.fields.StreamField([('paragraph', 0)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})})),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('sponsors', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='sponsors', to='people.sponsors')),
            ],
            options={
                'verbose_name': 'Athlet',
                'verbose_name_plural': 'Athletes',
            },
            bases=('wagtailcore.page',),
        ),
    ]
