# Generated by Django 5.0.9 on 2024-09-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletepage',
            name='birthdate',
            field=models.DateField(blank=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='athletepage',
            name='discipline',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sportart'),
        ),
        migrations.AlterField(
            model_name='athletepage',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nationalität'),
        ),
    ]
