# Generated by Django 5.0.9 on 2024-09-16 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_athletepage_birthdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athletepage',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='athletepage',
            name='sponsors',
        ),
    ]
