# Generated by Django 5.0.9 on 2024-09-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_remove_athletepage_bio_remove_athletepage_sponsors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletepage',
            name='birthdate',
            field=models.DateField(verbose_name='Geburtsdatum'),
        ),
    ]
