# Generated by Django 5.0.9 on 2024-09-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_athletepage_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athletepage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='athletepage',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='athletepage',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtsdatum'),
        ),
    ]
