# Generated by Django 5.0.9 on 2024-09-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_remove_athletepage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsors',
            name='image',
        ),
    ]
