# Generated by Django 5.0.9 on 2024-09-16 20:06

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_remove_sponsors_image'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('firstname', models.CharField(max_length=50, verbose_name='Vorname')),
                ('lastname', models.CharField(max_length=50, verbose_name='Nachname')),
                ('role', models.CharField(blank=True, max_length=50, verbose_name='Rolle')),
                ('consultation', models.TextField(blank=True, verbose_name='Sprechstunden')),
                ('competence', wagtail.fields.StreamField([('paragraph', 0)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})})),
                ('personal', wagtail.fields.StreamField([('paragraph', 0)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})})),
                ('career', wagtail.fields.StreamField([('step', 1)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('period', 0), ('description', 0)]], {'icon': 'time'})})),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Doktor',
                'verbose_name_plural': 'Doktoren',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Vorname')),
                ('lastname', models.CharField(max_length=50, verbose_name='Nachname')),
                ('role', models.CharField(blank=True, max_length=50, verbose_name='Rolle')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Mitarbeiter',
                'verbose_name_plural': 'Mitarbeitende',
            },
        ),
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('paragraph', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='AthletesIndexPage',
            new_name='DoctorIndexPage',
        ),
        migrations.RemoveField(
            model_name='athletepage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='Sponsors',
        ),
        migrations.DeleteModel(
            name='AthletePage',
        ),
    ]
