# Generated by Django 5.0.9 on 2024-09-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_doctorpage_teammember_teampage_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorIndexPage',
            new_name='AthletesIndexPage',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teampage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='DoctorPage',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='TeamPage',
        ),
    ]
