# Generated by Django 5.0.9 on 2024-09-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_remove_athletepage_lastname_athletepage_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletepage',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nationalität'),
        ),
    ]
