# Generated by Django 5.0.9 on 2024-09-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_athletepage_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletepage',
            name='career_start',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Karrierestart'),
        ),
    ]
