# Generated by Django 5.0.9 on 2024-09-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_athletepage_career_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampage',
            name='foundation_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Gründungsjahr'),
        ),
        migrations.AlterField(
            model_name='athletepage',
            name='sports',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sportart'),
        ),
    ]
