# Generated by Django 5.0.9 on 2024-09-18 18:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_teampage_foundation_year_alter_athletepage_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletesindexpage',
            name='services',
            field=wagtail.fields.StreamField([('paragraph', 0), ('service', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('service_title', 1), ('service_description', 1)]], {})}, null=True),
        ),
    ]
