# Generated by Django 5.0.9 on 2024-09-19 12:48

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_athletesindexpage_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletesindexpage',
            name='teaser',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Teaser'),
        ),
        migrations.AlterField(
            model_name='athletesindexpage',
            name='services',
            field=wagtail.fields.StreamField([('service', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold']}), 2: ('wagtail.blocks.StructBlock', [[('service_title', 0), ('service_description', 1)]], {})}, null=True),
        ),
    ]
