# Generated by Django 5.0.9 on 2024-09-19 13:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_alter_athletesindexpage_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletesindexpage',
            name='services',
            field=wagtail.fields.StreamField([('service', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold']}), 2: ('wagtail.blocks.StructBlock', [[('service_title', 0), ('service_description', 1)]], {})}, null=True),
        ),
    ]
