# Generated by Django 5.0.9 on 2024-09-19 16:34

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_athletesindexpage_header'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athletesindexpage',
            options={'verbose_name': 'Athleten & Teams', 'verbose_name_plural': 'Athleten & Teams'},
        ),
        migrations.CreateModel(
            name='BrandPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('teaser', models.TextField(blank=True, max_length=256, null=True, verbose_name='Teaser')),
                ('services', wagtail.fields.StreamField([('service', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold']}), 2: ('wagtail.blocks.StructBlock', [[('service_title', 0), ('service_description', 1)]], {})}, null=True)),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
            bases=('wagtailcore.page',),
        ),
    ]
