# Generated by Django 5.0.9 on 2024-09-19 16:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_alter_athletesindexpage_options_brandpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandpage',
            name='bio',
            field=wagtail.fields.StreamField([('paragraph', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}, null=True),
        ),
    ]
