# Generated by Django 5.0.9 on 2024-09-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_brandpage_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandpage',
            old_name='bio',
            new_name='intro',
        ),
    ]
