# Generated by Django 5.0.9 on 2024-09-19 16:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_remove_brandpage_intro_athletesindexpage_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athletesindexpage',
            name='bio',
        ),
        migrations.AddField(
            model_name='brandpage',
            name='bio',
            field=wagtail.fields.StreamField([('paragraph', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}, null=True),
        ),
    ]
