# Generated by Django 5.0.9 on 2024-09-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0025_contactpage_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon'),
        ),
    ]
