# Generated by Django 5.0.9 on 2024-09-19 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Startseite'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='value_heading',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='value'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='value_text',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='hero'),
        ),
    ]
