# Generated by Django 5.0.9 on 2024-09-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_hero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='value_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='value_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='value'),
        ),
    ]
