# Generated by Django 5.0.9 on 2024-09-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_value_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon'),
        ),
    ]
