# Generated by Django 5.0.9 on 2024-09-20 15:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_mail_homepage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bio',
            field=wagtail.fields.StreamField([('paragraph', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}, null=True),
        ),
    ]
